version: '3'
services:
  traefik:
    image: "docker.io/library/traefik:v2.10.4"
    command: --configfile /etc/traefik/config.toml
    ports:
      - 80:80
    volumes:
      - ./traefik/:/etc/traefik:ro

  unshorten-site:
    image: "docker.io/negrel/unshorten.site:latest"

  front:
    image: "docker.io/negrel/nginx-unshorten.site:latest"

