accesslog = true

[log]
level = "info"

[metrics]
[metrics.prometheus]

[api]
insecure = true

[providers]
[providers.file]
filename = "/etc/traefik/services.toml"

[entryPoints]
[entryPoints.traefik]
address = "127.0.0.1:8080"
[entryPoints.web]
address = ":80"
[entryPoints.websecure]
address = ":443"

# Enable ACME (Let's Encrypt): automatic SSL.
[certificatesResolvers.myresolver.acme]
# Email address used for registration.
email = "mail@example.com"
# File or key used for certificates storage.
storage = "/etc/traefik/acme.json"
# CA server to use.
# Uncomment the line to use Let's Encrypt's staging server,
# leave commented to go to prod.
#
# Optional
# Default: "https://acme-v02.api.letsencrypt.org/directory"
#
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[certificatesResolvers.myresolver.acme.httpChallenge]
# EntryPoint to use for the HTTP-01 challenges.
entryPoint = "web"

