[http.middlewares]
[http.middlewares.redirect-https.redirectScheme]
scheme = "https"
permanent = true

[http.routers]
[http.routers.front]
rule = "(Host(`www.unshorten.site`) || Host(`unshorten.site`)) && PathPrefix(`/`)"
service = "front"
middlewares = ["redirect-https"]
[http.routers.front.tls]
certResolver = "myresolver"

[http.routers.back]
rule = "(Host(`www.unshorten.site`) || Host(`unshorten.site`)) && PathPrefix(`/api/v1`)"
service = "back"
[http.routers.back.tls]
certResolver = "myresolver"

[http.routers.admin]
rule = "Host(`localhost`) && PathPrefix(`/admin`)"
service = "admin"

[http.services]
[http.services.front.loadBalancer]
passHostHeader = false
[[http.services.front.loadBalancer.servers]]
url = "http://front"

[http.services.back.loadBalancer]
[http.services.back.loadBalancer.healthCheck]
path = "/admin/health"
interval = "10s"
timeout = "3s"
[[http.services.back.loadBalancer.servers]]
url = "http://unshorten-site:8080"

[http.services.admin.loadBalancer]
[[http.services.admin.loadBalancer.servers]]
url = "http://unshorten-site:8080"

