version: '3'
services:
  traefik:
    image: "traefik:v2.10.4"
    command: --accesslog --log.level INFO --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  unshorten-site:
    image: "unshorten.site:dev"
    # Uncomment to use local debug binary instead of rebuilding entire image.
    command: /bin/unshorten-site
    volumes: # []
      # Uncomment to use local debug binary instead of rebuilding entire image.
      - ../server/target/debug/unshorten-site:/bin/unshorten-site:ro

    environment:
      UNSHORTEN_ADMIN_LOGIN: "admin"
      UNSHORTEN_ADMIN_PASSWORD: "admin"

    labels:
      - "traefik.http.routers.unshorten-site.rule=Host(`localhost`) && PathPrefix(`/api/v1`)"
      - "traefik.http.services.unshorten-site.loadbalancer.server.port=8080"

  front:
    image: "website-devserver:dev"
    working_dir: /app
    volumes:
      - .:/app/:rw
    labels:
      - "traefik.http.routers.front.rule=Host(`localhost`)"
      - "traefik.http.services.front.loadbalancer.server.port=1234"

