name: push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pipeline:
    if: "! contains(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - name: Docker build
        run: make docker/build
      - name: End to end tests
        run: make tests
      - run: docker save unshorten.site:dev > result
      - name: Store docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./result
          if-no-files-found: error

